### ISSUE TITLE
FR6. Rules Reference

### ISSUE THREAD

**Issue by bhohentanner** [WSU-4110/ScoreMania#4]
|FR6.  Rules Reference|
|---|
|**Goal**: The system will display a small rules reference for the players convenience.
**Stakeholders:** Customers|
| **Description:** When a customer presses a button from within a menu. A reference of common rules for the current game will become pop up for the player to read. |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 02/02/2022
|  **Priority:** 4 |

**Comment by OmarAlsaed01** [comment]
At the end, we figured that a rules reference page was unnecessary, as the app was pretty self explanatory if the user played the games we had trackers for. It's all displayed clearly on the screen. Had to scrap this idea.
